name: Update Contributions Badge
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get contributions
        run: |
          TOTAL=$(gh api graphql -f query='
          query {
            user(login: "${{ github.actor }}") {
              contributionsCollection(from: "2000-01-01T00:00:00Z", to: "2100-12-31T23:59:59Z") {
                contributionCalendar {
                  totalContributions
                }
              }
            }
          }' | jq '.data.user.contributionsCollection.contributionCalendar.totalContributions')
          echo "TOTAL_CONTRIBUTIONS=$TOTAL" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s/TOTAL_CONTRIBUTIONS_HERE/$TOTAL_CONTRIBUTIONS/" README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update contributions badge" || echo "No changes"
          git push
