name: Generate Contributions Image
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate contributions image
        run: |
          TOTAL=$(gh api users/${{ github.actor }}/repos --paginate | jq '[.[] | select(.fork == false) | .stargazers_count] | add')
          echo "Total contributions: $TOTAL"
          convert -size 600x200 xc:none -gravity center -font Arial -pointsize 40 -fill '#FF0080' -annotate 0 "Total Contributions: $TOTAL" contributions.png

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: contributions-image
          path: contributions.png
